# Automatically generated, to update run again the generator from the torch root path
# nim c -r torch/generator.nim
proc storage_offset*(self: Tensor): int64 {.inline.} = self.dynamicCppCall("storage_offset").to(int64)
proc set_u*(self: Tensor, source: Tensor): Tensor {.inline.} = self.dynamicCppCall("set_", source).to(Tensor)
proc set_u*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("set_").to(Tensor)
proc u_fill_u*(self: Tensor, value: float): Tensor {.inline.} = self.dynamicCppCall("_fill_", value).to(Tensor)
proc u_fill_u*(self: Tensor, value: Tensor): Tensor {.inline.} = self.dynamicCppCall("_fill_", value).to(Tensor)
proc is_contiguous*(self: Tensor): bool {.inline.} = self.dynamicCppCall("is_contiguous").to(bool)
proc is_set_to*(self: Tensor, tensor: Tensor): bool {.inline.} = self.dynamicCppCall("is_set_to", tensor).to(bool)
proc masked_fill_u*(self: Tensor, mask: Tensor, value: float): Tensor {.inline.} = self.dynamicCppCall("masked_fill_", mask, value).to(Tensor)
proc masked_fill_u*(self: Tensor, mask: Tensor, value: Tensor): Tensor {.inline.} = self.dynamicCppCall("masked_fill_", mask, value).to(Tensor)
proc masked_scatter_u*(self: Tensor, mask: Tensor, source: Tensor): Tensor {.inline.} = self.dynamicCppCall("masked_scatter_", mask, source).to(Tensor)
proc masked_select*(self: Tensor, mask: Tensor): Tensor {.inline.} = self.dynamicCppCall("masked_select", mask).to(Tensor)
proc nonzero*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("nonzero").to(Tensor)
proc contiguous*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("contiguous").to(Tensor)
proc index_select*(self: Tensor, dim: int64, index: Tensor): Tensor {.inline.} = self.dynamicCppCall("index_select", dim, index).to(Tensor)
proc u_indexCopy_u*(self: Tensor, dim: int64, index: Tensor, source: Tensor): Tensor {.inline.} = self.dynamicCppCall("_indexCopy_", dim, index, source).to(Tensor)
proc take*(self: Tensor, index: Tensor): Tensor {.inline.} = self.dynamicCppCall("take", index).to(Tensor)
proc put_u*(self: Tensor, index: Tensor, source: Tensor, accumulate: bool = false): Tensor {.inline.} = self.dynamicCppCall("put_", index, source, accumulate).to(Tensor)
proc index_add_u*(self: Tensor, dim: int64, index: Tensor, source: Tensor): Tensor {.inline.} = self.dynamicCppCall("index_add_", dim, index, source).to(Tensor)
proc index_fill_u*(self: Tensor, dim: int64, index: Tensor, value: float): Tensor {.inline.} = self.dynamicCppCall("index_fill_", dim, index, value).to(Tensor)
proc index_fill_u*(self: Tensor, dim: int64, index: Tensor, value: Tensor): Tensor {.inline.} = self.dynamicCppCall("index_fill_", dim, index, value).to(Tensor)
proc unfold*(self: Tensor, dimension: int64, size: int64, step: int64): Tensor {.inline.} = self.dynamicCppCall("unfold", dimension, size, step).to(Tensor)
proc scatter_u*(self: Tensor, dim: int64, index: Tensor, src: Tensor): Tensor {.inline.} = self.dynamicCppCall("scatter_", dim, index, src).to(Tensor)
proc scatter_u*(self: Tensor, dim: int64, index: Tensor, value: float): Tensor {.inline.} = self.dynamicCppCall("scatter_", dim, index, value).to(Tensor)
proc scatter_add_u*(self: Tensor, dim: int64, index: Tensor, src: Tensor): Tensor {.inline.} = self.dynamicCppCall("scatter_add_", dim, index, src).to(Tensor)
proc gather*(self: Tensor, dim: int64, index: Tensor): Tensor {.inline.} = self.dynamicCppCall("gather", dim, index).to(Tensor)
proc equal*(self: Tensor, other: Tensor): bool {.inline.} = self.dynamicCppCall("equal", other).to(bool)
proc u_u_and_u_u*(self: Tensor, other: float): Tensor {.inline.} = self.dynamicCppCall("__and__", other).to(Tensor)
proc u_u_and_u_u*(self: Tensor, other: Tensor): Tensor {.inline.} = self.dynamicCppCall("__and__", other).to(Tensor)
proc u_u_iand_u_u*(self: Tensor, other: float): Tensor {.inline.} = self.dynamicCppCall("__iand__", other).to(Tensor)
proc u_u_iand_u_u*(self: Tensor, other: Tensor): Tensor {.inline.} = self.dynamicCppCall("__iand__", other).to(Tensor)
proc u_u_or_u_u*(self: Tensor, other: float): Tensor {.inline.} = self.dynamicCppCall("__or__", other).to(Tensor)
proc u_u_or_u_u*(self: Tensor, other: Tensor): Tensor {.inline.} = self.dynamicCppCall("__or__", other).to(Tensor)
proc u_u_ior_u_u*(self: Tensor, other: float): Tensor {.inline.} = self.dynamicCppCall("__ior__", other).to(Tensor)
proc u_u_ior_u_u*(self: Tensor, other: Tensor): Tensor {.inline.} = self.dynamicCppCall("__ior__", other).to(Tensor)
proc u_u_xor_u_u*(self: Tensor, other: float): Tensor {.inline.} = self.dynamicCppCall("__xor__", other).to(Tensor)
proc u_u_xor_u_u*(self: Tensor, other: Tensor): Tensor {.inline.} = self.dynamicCppCall("__xor__", other).to(Tensor)
proc u_u_ixor_u_u*(self: Tensor, other: float): Tensor {.inline.} = self.dynamicCppCall("__ixor__", other).to(Tensor)
proc u_u_ixor_u_u*(self: Tensor, other: Tensor): Tensor {.inline.} = self.dynamicCppCall("__ixor__", other).to(Tensor)
proc u_u_lshift_u_u*(self: Tensor, other: float): Tensor {.inline.} = self.dynamicCppCall("__lshift__", other).to(Tensor)
proc u_u_lshift_u_u*(self: Tensor, other: Tensor): Tensor {.inline.} = self.dynamicCppCall("__lshift__", other).to(Tensor)
proc u_u_ilshift_u_u*(self: Tensor, other: float): Tensor {.inline.} = self.dynamicCppCall("__ilshift__", other).to(Tensor)
proc u_u_ilshift_u_u*(self: Tensor, other: Tensor): Tensor {.inline.} = self.dynamicCppCall("__ilshift__", other).to(Tensor)
proc u_u_rshift_u_u*(self: Tensor, other: float): Tensor {.inline.} = self.dynamicCppCall("__rshift__", other).to(Tensor)
proc u_u_rshift_u_u*(self: Tensor, other: Tensor): Tensor {.inline.} = self.dynamicCppCall("__rshift__", other).to(Tensor)
proc u_u_irshift_u_u*(self: Tensor, other: float): Tensor {.inline.} = self.dynamicCppCall("__irshift__", other).to(Tensor)
proc u_u_irshift_u_u*(self: Tensor, other: Tensor): Tensor {.inline.} = self.dynamicCppCall("__irshift__", other).to(Tensor)
proc lt*(self: Tensor, other: float): Tensor {.inline.} = self.dynamicCppCall("lt", other).to(Tensor)
proc lt*(self: Tensor, other: Tensor): Tensor {.inline.} = self.dynamicCppCall("lt", other).to(Tensor)
proc lt_u*(self: Tensor, other: float): Tensor {.inline.} = self.dynamicCppCall("lt_", other).to(Tensor)
proc lt_u*(self: Tensor, other: Tensor): Tensor {.inline.} = self.dynamicCppCall("lt_", other).to(Tensor)
proc gt*(self: Tensor, other: float): Tensor {.inline.} = self.dynamicCppCall("gt", other).to(Tensor)
proc gt*(self: Tensor, other: Tensor): Tensor {.inline.} = self.dynamicCppCall("gt", other).to(Tensor)
proc gt_u*(self: Tensor, other: float): Tensor {.inline.} = self.dynamicCppCall("gt_", other).to(Tensor)
proc gt_u*(self: Tensor, other: Tensor): Tensor {.inline.} = self.dynamicCppCall("gt_", other).to(Tensor)
proc le*(self: Tensor, other: float): Tensor {.inline.} = self.dynamicCppCall("le", other).to(Tensor)
proc le*(self: Tensor, other: Tensor): Tensor {.inline.} = self.dynamicCppCall("le", other).to(Tensor)
proc le_u*(self: Tensor, other: float): Tensor {.inline.} = self.dynamicCppCall("le_", other).to(Tensor)
proc le_u*(self: Tensor, other: Tensor): Tensor {.inline.} = self.dynamicCppCall("le_", other).to(Tensor)
proc ge*(self: Tensor, other: float): Tensor {.inline.} = self.dynamicCppCall("ge", other).to(Tensor)
proc ge*(self: Tensor, other: Tensor): Tensor {.inline.} = self.dynamicCppCall("ge", other).to(Tensor)
proc ge_u*(self: Tensor, other: float): Tensor {.inline.} = self.dynamicCppCall("ge_", other).to(Tensor)
proc ge_u*(self: Tensor, other: Tensor): Tensor {.inline.} = self.dynamicCppCall("ge_", other).to(Tensor)
proc eq*(self: Tensor, other: float): Tensor {.inline.} = self.dynamicCppCall("eq", other).to(Tensor)
proc eq*(self: Tensor, other: Tensor): Tensor {.inline.} = self.dynamicCppCall("eq", other).to(Tensor)
proc eq_u*(self: Tensor, other: float): Tensor {.inline.} = self.dynamicCppCall("eq_", other).to(Tensor)
proc eq_u*(self: Tensor, other: Tensor): Tensor {.inline.} = self.dynamicCppCall("eq_", other).to(Tensor)
proc ne*(self: Tensor, other: float): Tensor {.inline.} = self.dynamicCppCall("ne", other).to(Tensor)
proc ne*(self: Tensor, other: Tensor): Tensor {.inline.} = self.dynamicCppCall("ne", other).to(Tensor)
proc ne_u*(self: Tensor, other: float): Tensor {.inline.} = self.dynamicCppCall("ne_", other).to(Tensor)
proc ne_u*(self: Tensor, other: Tensor): Tensor {.inline.} = self.dynamicCppCall("ne_", other).to(Tensor)
proc min*(self: Tensor, other: Tensor): Tensor {.inline.} = self.dynamicCppCall("min", other).to(Tensor)
proc min*(self: Tensor): float {.inline.} = self.dynamicCppCall("min").to(float)
proc max*(self: Tensor, other: Tensor): Tensor {.inline.} = self.dynamicCppCall("max", other).to(Tensor)
proc max*(self: Tensor): float {.inline.} = self.dynamicCppCall("max").to(float)
proc median*(self: Tensor): float {.inline.} = self.dynamicCppCall("median").to(float)
proc all*(self: Tensor): float {.inline.} = self.dynamicCppCall("all").to(float)
proc u_th_all*(self: Tensor, dim: int64, keepdim: bool = false): Tensor {.inline.} = self.dynamicCppCall("_th_all", dim, keepdim).to(Tensor)
proc any*(self: Tensor): float {.inline.} = self.dynamicCppCall("any").to(float)
proc u_th_any*(self: Tensor, dim: int64, keepdim: bool = false): Tensor {.inline.} = self.dynamicCppCall("_th_any", dim, keepdim).to(Tensor)
proc u_abs*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("_abs").to(Tensor)
proc u_th_sigmoid*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("_th_sigmoid").to(Tensor)
proc u_log*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("_log").to(Tensor)
proc u_log10*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("_log10").to(Tensor)
proc u_log1p*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("_log1p").to(Tensor)
proc u_log2*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("_log2").to(Tensor)
proc lgamma*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("lgamma").to(Tensor)
proc lgamma_u*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("lgamma_").to(Tensor)
proc digamma*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("digamma").to(Tensor)
proc digamma_u*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("digamma_").to(Tensor)
proc polygamma*(self: Tensor, n: int64): Tensor {.inline.} = self.dynamicCppCall("polygamma", n).to(Tensor)
proc polygamma_u*(self: Tensor, n: int64): Tensor {.inline.} = self.dynamicCppCall("polygamma_", n).to(Tensor)
proc u_exp*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("_exp").to(Tensor)
proc u_expm1*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("_expm1").to(Tensor)
proc u_cos*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("_cos").to(Tensor)
proc u_acos*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("_acos").to(Tensor)
proc u_cosh*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("_cosh").to(Tensor)
proc u_sin*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("_sin").to(Tensor)
proc u_asin*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("_asin").to(Tensor)
proc u_sinh*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("_sinh").to(Tensor)
proc u_tan*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("_tan").to(Tensor)
proc u_atan*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("_atan").to(Tensor)
proc u_th_tanh*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("_th_tanh").to(Tensor)
proc u_erf*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("_erf").to(Tensor)
proc u_erfc*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("_erfc").to(Tensor)
proc erfinv_u*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("erfinv_").to(Tensor)
proc erfinv*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("erfinv").to(Tensor)
proc u_sqrt*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("_sqrt").to(Tensor)
proc u_rsqrt*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("_rsqrt").to(Tensor)
proc u_ceil*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("_ceil").to(Tensor)
proc u_floor*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("_floor").to(Tensor)
proc u_round*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("_round").to(Tensor)
proc u_trunc*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("_trunc").to(Tensor)
proc frac_u*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("frac_").to(Tensor)
proc frac*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("frac").to(Tensor)
proc u_th_var*(self: Tensor, dim: int64, unbiased: bool = true, keepdim: bool = false): Tensor {.inline.} = self.dynamicCppCall("_th_var", dim, unbiased, keepdim).to(Tensor)
proc u_th_std*(self: Tensor, dim: int64, unbiased: bool = true, keepdim: bool = false): Tensor {.inline.} = self.dynamicCppCall("_th_std", dim, unbiased, keepdim).to(Tensor)
proc u_th_norm*(self: Tensor, p: float, dim: int64, keepdim: bool = false): Tensor {.inline.} = self.dynamicCppCall("_th_norm", p, dim, keepdim).to(Tensor)
proc renorm*(self: Tensor, p: float, dim: int64, maxnorm: float): Tensor {.inline.} = self.dynamicCppCall("renorm", p, dim, maxnorm).to(Tensor)
proc renorm_u*(self: Tensor, p: float, dim: int64, maxnorm: float): Tensor {.inline.} = self.dynamicCppCall("renorm_", p, dim, maxnorm).to(Tensor)
proc reciprocal*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("reciprocal").to(Tensor)
proc reciprocal_u*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("reciprocal_").to(Tensor)
proc neg*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("neg").to(Tensor)
proc neg_u*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("neg_").to(Tensor)
proc atan2*(self: Tensor, other: Tensor): Tensor {.inline.} = self.dynamicCppCall("atan2", other).to(Tensor)
proc atan2_u*(self: Tensor, other: Tensor): Tensor {.inline.} = self.dynamicCppCall("atan2_", other).to(Tensor)
proc pow*(self: Tensor, exponent: Tensor): Tensor {.inline.} = self.dynamicCppCall("pow", exponent).to(Tensor)
proc pow_u*(self: Tensor, exponent: float): Tensor {.inline.} = self.dynamicCppCall("pow_", exponent).to(Tensor)
proc pow_u*(self: Tensor, exponent: Tensor): Tensor {.inline.} = self.dynamicCppCall("pow_", exponent).to(Tensor)
proc lerp*(self: Tensor, aend: Tensor, weight: float): Tensor {.inline.} = self.dynamicCppCall("lerp", aend, weight).to(Tensor)
proc lerp_u*(self: Tensor, aend: Tensor, weight: float): Tensor {.inline.} = self.dynamicCppCall("lerp_", aend, weight).to(Tensor)
proc histc*(self: Tensor, bins: int64 = 100, min: float = 0, max: float = 0): Tensor {.inline.} = self.dynamicCppCall("histc", bins, min, max).to(Tensor)
proc u_th_sum*(self: Tensor, dim: int64, keepdim: bool = false): Tensor {.inline.} = self.dynamicCppCall("_th_sum", dim, keepdim).to(Tensor)
proc u_th_prod*(self: Tensor, dim: int64, keepdim: bool = false): Tensor {.inline.} = self.dynamicCppCall("_th_prod", dim, keepdim).to(Tensor)
proc u_cumsum*(self: Tensor, dim: int64): Tensor {.inline.} = self.dynamicCppCall("_cumsum", dim).to(Tensor)
proc u_cumprod*(self: Tensor, dim: int64): Tensor {.inline.} = self.dynamicCppCall("_cumprod", dim).to(Tensor)
proc sign*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("sign").to(Tensor)
proc sign_u*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("sign_").to(Tensor)
proc fmod*(self: Tensor, other: float): Tensor {.inline.} = self.dynamicCppCall("fmod", other).to(Tensor)
proc fmod*(self: Tensor, other: Tensor): Tensor {.inline.} = self.dynamicCppCall("fmod", other).to(Tensor)
proc fmod_u*(self: Tensor, other: float): Tensor {.inline.} = self.dynamicCppCall("fmod_", other).to(Tensor)
proc fmod_u*(self: Tensor, other: Tensor): Tensor {.inline.} = self.dynamicCppCall("fmod_", other).to(Tensor)
proc remainder*(self: Tensor, other: float): Tensor {.inline.} = self.dynamicCppCall("remainder", other).to(Tensor)
proc remainder*(self: Tensor, other: Tensor): Tensor {.inline.} = self.dynamicCppCall("remainder", other).to(Tensor)
proc remainder_u*(self: Tensor, other: float): Tensor {.inline.} = self.dynamicCppCall("remainder_", other).to(Tensor)
proc remainder_u*(self: Tensor, other: Tensor): Tensor {.inline.} = self.dynamicCppCall("remainder_", other).to(Tensor)
proc u_th_clamp_u*(self: Tensor, min: float, max: float): Tensor {.inline.} = self.dynamicCppCall("_th_clamp_", min, max).to(Tensor)
proc u_th_clamp_min_u*(self: Tensor, min: float): Tensor {.inline.} = self.dynamicCppCall("_th_clamp_min_", min).to(Tensor)
proc u_th_clamp_max_u*(self: Tensor, max: float): Tensor {.inline.} = self.dynamicCppCall("_th_clamp_max_", max).to(Tensor)
proc tril*(self: Tensor, diagonal: int64 = 0): Tensor {.inline.} = self.dynamicCppCall("tril", diagonal).to(Tensor)
proc tril_u*(self: Tensor, diagonal: int64 = 0): Tensor {.inline.} = self.dynamicCppCall("tril_", diagonal).to(Tensor)
proc triu*(self: Tensor, diagonal: int64 = 0): Tensor {.inline.} = self.dynamicCppCall("triu", diagonal).to(Tensor)
proc triu_u*(self: Tensor, diagonal: int64 = 0): Tensor {.inline.} = self.dynamicCppCall("triu_", diagonal).to(Tensor)
proc cross*(self: Tensor, other: Tensor, dim: int64 = -1): Tensor {.inline.} = self.dynamicCppCall("cross", other, dim).to(Tensor)
proc diag*(self: Tensor, diagonal: int64 = 0): Tensor {.inline.} = self.dynamicCppCall("diag", diagonal).to(Tensor)
proc u_addmv*(self: Tensor, mat: Tensor, vec: Tensor, beta: float = 1, alpha: float = 1): Tensor {.inline.} = self.dynamicCppCall("_addmv", mat, vec, beta, alpha).to(Tensor)
proc u_addmv_u*(self: Tensor, mat: Tensor, vec: Tensor, beta: float = 1, alpha: float = 1): Tensor {.inline.} = self.dynamicCppCall("_addmv_", mat, vec, beta, alpha).to(Tensor)
proc u_addr*(self: Tensor, vec1: Tensor, vec2: Tensor, beta: float = 1, alpha: float = 1): Tensor {.inline.} = self.dynamicCppCall("_addr", vec1, vec2, beta, alpha).to(Tensor)
proc u_addr_u*(self: Tensor, vec1: Tensor, vec2: Tensor, beta: float = 1, alpha: float = 1): Tensor {.inline.} = self.dynamicCppCall("_addr_", vec1, vec2, beta, alpha).to(Tensor)
proc u_ger*(self: Tensor, vec2: Tensor): Tensor {.inline.} = self.dynamicCppCall("_ger", vec2).to(Tensor)
proc u_mv*(self: Tensor, vec: Tensor): Tensor {.inline.} = self.dynamicCppCall("_mv", vec).to(Tensor)
proc u_mm*(self: Tensor, mat2: Tensor): Tensor {.inline.} = self.dynamicCppCall("_mm", mat2).to(Tensor)
proc bmm*(self: Tensor, mat2: Tensor): Tensor {.inline.} = self.dynamicCppCall("bmm", mat2).to(Tensor)
proc addbmm*(self: Tensor, batch1: Tensor, batch2: Tensor, beta: float = 1, alpha: float = 1): Tensor {.inline.} = self.dynamicCppCall("addbmm", batch1, batch2, beta, alpha).to(Tensor)
proc addbmm_u*(self: Tensor, batch1: Tensor, batch2: Tensor, beta: float = 1, alpha: float = 1): Tensor {.inline.} = self.dynamicCppCall("addbmm_", batch1, batch2, beta, alpha).to(Tensor)
proc baddbmm*(self: Tensor, batch1: Tensor, batch2: Tensor, beta: float = 1, alpha: float = 1): Tensor {.inline.} = self.dynamicCppCall("baddbmm", batch1, batch2, beta, alpha).to(Tensor)
proc baddbmm_u*(self: Tensor, batch1: Tensor, batch2: Tensor, beta: float = 1, alpha: float = 1): Tensor {.inline.} = self.dynamicCppCall("baddbmm_", batch1, batch2, beta, alpha).to(Tensor)
proc addcmul*(self: Tensor, tensor1: Tensor, tensor2: Tensor, value: float = 1): Tensor {.inline.} = self.dynamicCppCall("addcmul", tensor1, tensor2, value).to(Tensor)
proc addcmul_u*(self: Tensor, tensor1: Tensor, tensor2: Tensor, value: float = 1): Tensor {.inline.} = self.dynamicCppCall("addcmul_", tensor1, tensor2, value).to(Tensor)
proc addcdiv*(self: Tensor, tensor1: Tensor, tensor2: Tensor, value: float = 1): Tensor {.inline.} = self.dynamicCppCall("addcdiv", tensor1, tensor2, value).to(Tensor)
proc addcdiv_u*(self: Tensor, tensor1: Tensor, tensor2: Tensor, value: float = 1): Tensor {.inline.} = self.dynamicCppCall("addcdiv_", tensor1, tensor2, value).to(Tensor)
proc potrs*(self: Tensor, input2: Tensor, upper: bool = true): Tensor {.inline.} = self.dynamicCppCall("potrs", input2, upper).to(Tensor)
proc orgqr*(self: Tensor, input2: Tensor): Tensor {.inline.} = self.dynamicCppCall("orgqr", input2).to(Tensor)
proc ormqr*(self: Tensor, input2: Tensor, input3: Tensor, left: bool = true, transpose: bool = false): Tensor {.inline.} = self.dynamicCppCall("ormqr", input2, input3, left, transpose).to(Tensor)
proc u_copy_ignoring_overlaps_u*(self: Tensor, src: Tensor): Tensor {.inline.} = self.dynamicCppCall("_copy_ignoring_overlaps_", src).to(Tensor)
proc u_cast_Byte*(self: Tensor, non_blocking: bool = false): Tensor {.inline.} = self.dynamicCppCall("_cast_Byte", non_blocking).to(Tensor)
proc u_cast_Char*(self: Tensor, non_blocking: bool = false): Tensor {.inline.} = self.dynamicCppCall("_cast_Char", non_blocking).to(Tensor)
proc u_cast_Double*(self: Tensor, non_blocking: bool = false): Tensor {.inline.} = self.dynamicCppCall("_cast_Double", non_blocking).to(Tensor)
proc u_cast_Float*(self: Tensor, non_blocking: bool = false): Tensor {.inline.} = self.dynamicCppCall("_cast_Float", non_blocking).to(Tensor)
proc u_cast_Int*(self: Tensor, non_blocking: bool = false): Tensor {.inline.} = self.dynamicCppCall("_cast_Int", non_blocking).to(Tensor)
proc u_cast_Long*(self: Tensor, non_blocking: bool = false): Tensor {.inline.} = self.dynamicCppCall("_cast_Long", non_blocking).to(Tensor)
proc u_cast_Short*(self: Tensor, non_blocking: bool = false): Tensor {.inline.} = self.dynamicCppCall("_cast_Short", non_blocking).to(Tensor)
proc u_cast_Half*(self: Tensor, non_blocking: bool = false): Tensor {.inline.} = self.dynamicCppCall("_cast_Half", non_blocking).to(Tensor)
proc abs*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("abs").to(Tensor)
proc abs_u*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("abs_").to(Tensor)
proc acos*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("acos").to(Tensor)
proc acos_u*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("acos_").to(Tensor)
proc all*(self: Tensor, dim: int64, keepdim: bool = false): Tensor {.inline.} = self.dynamicCppCall("all", dim, keepdim).to(Tensor)
proc any*(self: Tensor, dim: int64, keepdim: bool = false): Tensor {.inline.} = self.dynamicCppCall("any", dim, keepdim).to(Tensor)
proc argmax*(self: Tensor, dim: int64, keepdim: bool = false): Tensor {.inline.} = self.dynamicCppCall("argmax", dim, keepdim).to(Tensor)
proc argmax*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("argmax").to(Tensor)
proc u_argmax*(self: Tensor, dim: int64, keepdim: bool = false): Tensor {.inline.} = self.dynamicCppCall("_argmax", dim, keepdim).to(Tensor)
proc argmin*(self: Tensor, dim: int64, keepdim: bool = false): Tensor {.inline.} = self.dynamicCppCall("argmin", dim, keepdim).to(Tensor)
proc argmin*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("argmin").to(Tensor)
proc u_argmin*(self: Tensor, dim: int64, keepdim: bool = false): Tensor {.inline.} = self.dynamicCppCall("_argmin", dim, keepdim).to(Tensor)
proc asin*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("asin").to(Tensor)
proc asin_u*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("asin_").to(Tensor)
proc atan*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("atan").to(Tensor)
proc atan_u*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("atan_").to(Tensor)
proc bernoulli*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("bernoulli").to(Tensor)
proc bernoulli_u*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("bernoulli_").to(Tensor)
proc bincount*(self: Tensor, weights: Tensor, minlength: int64 = 0): Tensor {.inline.} = self.dynamicCppCall("bincount", weights, minlength).to(Tensor)
proc ceil*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("ceil").to(Tensor)
proc ceil_u*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("ceil_").to(Tensor)
proc chunk*(self: Tensor, chunks: int64, dim: int64 = 0): TensorList {.inline.} = self.dynamicCppCall("chunk", chunks, dim).to(TensorList)
proc conv_tbc*(self: Tensor, weight: Tensor, bias: Tensor, pad: int64): Tensor {.inline.} = self.dynamicCppCall("conv_tbc", weight, bias, pad).to(Tensor)
proc cos*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("cos").to(Tensor)
proc cos_u*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("cos_").to(Tensor)
proc cosh*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("cosh").to(Tensor)
proc cosh_u*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("cosh_").to(Tensor)
proc cumsum*(self: Tensor, dim: int64): Tensor {.inline.} = self.dynamicCppCall("cumsum", dim).to(Tensor)
proc cumprod*(self: Tensor, dim: int64): Tensor {.inline.} = self.dynamicCppCall("cumprod", dim).to(Tensor)
proc det*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("det").to(Tensor)
proc diagonal*(self: Tensor, offset: int64 = 0, dim1: int64 = 0, dim2: int64 = 1): Tensor {.inline.} = self.dynamicCppCall("diagonal", offset, dim1, dim2).to(Tensor)
proc adiv*(self: Tensor, other: Tensor): Tensor {.inline.} = self.dynamicCppCall("div", other).to(Tensor)
proc div_u*(self: Tensor, other: Tensor): Tensor {.inline.} = self.dynamicCppCall("div_", other).to(Tensor)
proc dot*(self: Tensor, tensor: Tensor): Tensor {.inline.} = self.dynamicCppCall("dot", tensor).to(Tensor)
proc erf*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("erf").to(Tensor)
proc erf_u*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("erf_").to(Tensor)
proc erfc*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("erfc").to(Tensor)
proc erfc_u*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("erfc_").to(Tensor)
proc exp*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("exp").to(Tensor)
proc exp_u*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("exp_").to(Tensor)
proc expm1*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("expm1").to(Tensor)
proc expm1_u*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("expm1_").to(Tensor)
proc expand_as*(self: Tensor, other: Tensor): Tensor {.inline.} = self.dynamicCppCall("expand_as", other).to(Tensor)
proc flatten*(self: Tensor, start_dim: int64 = 0, end_dim: int64 = -1): Tensor {.inline.} = self.dynamicCppCall("flatten", start_dim, end_dim).to(Tensor)
proc fill_u*(self: Tensor, value: Tensor): Tensor {.inline.} = self.dynamicCppCall("fill_", value).to(Tensor)
proc floor*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("floor").to(Tensor)
proc floor_u*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("floor_").to(Tensor)
proc ger*(self: Tensor, vec2: Tensor): Tensor {.inline.} = self.dynamicCppCall("ger", vec2).to(Tensor)
proc fft*(self: Tensor, signal_ndim: int64, normalized: bool = false): Tensor {.inline.} = self.dynamicCppCall("fft", signal_ndim, normalized).to(Tensor)
proc ifft*(self: Tensor, signal_ndim: int64, normalized: bool = false): Tensor {.inline.} = self.dynamicCppCall("ifft", signal_ndim, normalized).to(Tensor)
proc rfft*(self: Tensor, signal_ndim: int64, normalized: bool = false, onesided: bool = true): Tensor {.inline.} = self.dynamicCppCall("rfft", signal_ndim, normalized, onesided).to(Tensor)
proc index*(self: Tensor, indices: TensorList): Tensor {.inline.} = self.dynamicCppCall("index", indices).to(Tensor)
proc index_copy_u*(self: Tensor, dim: int64, index: Tensor, source: Tensor): Tensor {.inline.} = self.dynamicCppCall("index_copy_", dim, index, source).to(Tensor)
proc index_put*(self: Tensor, indices: TensorList, values: Tensor): Tensor {.inline.} = self.dynamicCppCall("index_put", indices, values).to(Tensor)
proc index_put_u*(self: Tensor, indices: TensorList, values: Tensor): Tensor {.inline.} = self.dynamicCppCall("index_put_", indices, values).to(Tensor)
proc inverse*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("inverse").to(Tensor)
proc is_cuda*(self: Tensor): bool {.inline.} = self.dynamicCppCall("is_cuda").to(bool)
proc is_distributed*(self: Tensor): bool {.inline.} = self.dynamicCppCall("is_distributed").to(bool)
proc is_floating_point*(self: Tensor): bool {.inline.} = self.dynamicCppCall("is_floating_point").to(bool)
proc is_nonzero*(self: Tensor): bool {.inline.} = self.dynamicCppCall("is_nonzero").to(bool)
proc is_same_size*(self: Tensor, other: Tensor): bool {.inline.} = self.dynamicCppCall("is_same_size", other).to(bool)
proc is_signed*(self: Tensor): bool {.inline.} = self.dynamicCppCall("is_signed").to(bool)
proc is_sparse*(self: Tensor): bool {.inline.} = self.dynamicCppCall("is_sparse").to(bool)
proc log*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("log").to(Tensor)
proc log_u*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("log_").to(Tensor)
proc log10*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("log10").to(Tensor)
proc log10_u*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("log10_").to(Tensor)
proc log1p*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("log1p").to(Tensor)
proc log1p_u*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("log1p_").to(Tensor)
proc log2*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("log2").to(Tensor)
proc log2_u*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("log2_").to(Tensor)
proc logdet*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("logdet").to(Tensor)
proc log_softmax*(self: Tensor, dim: int64): Tensor {.inline.} = self.dynamicCppCall("log_softmax", dim).to(Tensor)
proc log_softmax_backward_data*(self: Tensor, grad_output: Tensor, output: Tensor, dim: int64): Tensor {.inline.} = self.dynamicCppCall("log_softmax_backward_data", grad_output, output, dim).to(Tensor)
proc logsumexp*(self: Tensor, dim: int64, keepdim: bool = false): Tensor {.inline.} = self.dynamicCppCall("logsumexp", dim, keepdim).to(Tensor)
proc matmul*(self: Tensor, other: Tensor): Tensor {.inline.} = self.dynamicCppCall("matmul", other).to(Tensor)
proc max_values*(self: Tensor, dim: int64, keepdim: bool = false): Tensor {.inline.} = self.dynamicCppCall("max_values", dim, keepdim).to(Tensor)
proc mean*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("mean").to(Tensor)
proc mean*(self: Tensor, dim: int64, keepdim: bool = false): Tensor {.inline.} = self.dynamicCppCall("mean", dim, keepdim).to(Tensor)
proc min_values*(self: Tensor, dim: int64, keepdim: bool = false): Tensor {.inline.} = self.dynamicCppCall("min_values", dim, keepdim).to(Tensor)
proc mm*(self: Tensor, mat2: Tensor): Tensor {.inline.} = self.dynamicCppCall("mm", mat2).to(Tensor)
proc mul*(self: Tensor, other: Tensor): Tensor {.inline.} = self.dynamicCppCall("mul", other).to(Tensor)
proc mul_u*(self: Tensor, other: Tensor): Tensor {.inline.} = self.dynamicCppCall("mul_", other).to(Tensor)
proc mv*(self: Tensor, vec: Tensor): Tensor {.inline.} = self.dynamicCppCall("mv", vec).to(Tensor)
proc mvlgamma*(self: Tensor, p: int64): Tensor {.inline.} = self.dynamicCppCall("mvlgamma", p).to(Tensor)
proc mvlgamma_u*(self: Tensor, p: int64): Tensor {.inline.} = self.dynamicCppCall("mvlgamma_", p).to(Tensor)
proc narrow*(self: Tensor, dim: int64, start: int64, length: int64): Tensor {.inline.} = self.dynamicCppCall("narrow", dim, start, length).to(Tensor)
proc pin_memory*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("pin_memory").to(Tensor)
proc reshape_as*(self: Tensor, other: Tensor): Tensor {.inline.} = self.dynamicCppCall("reshape_as", other).to(Tensor)
proc round*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("round").to(Tensor)
proc round_u*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("round_").to(Tensor)
proc relu*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("relu").to(Tensor)
proc relu_u*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("relu_").to(Tensor)
proc rsqrt*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("rsqrt").to(Tensor)
proc rsqrt_u*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("rsqrt_").to(Tensor)
proc select*(self: Tensor, dim: int64, index: int64): Tensor {.inline.} = self.dynamicCppCall("select", dim, index).to(Tensor)
proc sigmoid*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("sigmoid").to(Tensor)
proc sigmoid_u*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("sigmoid_").to(Tensor)
proc sin*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("sin").to(Tensor)
proc sin_u*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("sin_").to(Tensor)
proc sinh*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("sinh").to(Tensor)
proc sinh_u*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("sinh_").to(Tensor)
proc size*(self: Tensor, dim: int64): int64 {.inline.} = self.dynamicCppCall("size", dim).to(int64)
proc slice*(self: Tensor, dim: int64 = 0, start: int64 = 0, aend: int64 = 9223372036854775807, step: int64 = 1): Tensor {.inline.} = self.dynamicCppCall("slice", dim, start, aend, step).to(Tensor)
proc smm*(self: Tensor, mat2: Tensor): Tensor {.inline.} = self.dynamicCppCall("smm", mat2).to(Tensor)
proc softmax*(self: Tensor, dim: int64): Tensor {.inline.} = self.dynamicCppCall("softmax", dim).to(Tensor)
proc softmax_backward_data*(self: Tensor, grad_output: Tensor, output: Tensor, dim: int64): Tensor {.inline.} = self.dynamicCppCall("softmax_backward_data", grad_output, output, dim).to(Tensor)
proc split*(self: Tensor, split_size: int64, dim: int64 = 0): TensorList {.inline.} = self.dynamicCppCall("split", split_size, dim).to(TensorList)
proc squeeze*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("squeeze").to(Tensor)
proc squeeze*(self: Tensor, dim: int64): Tensor {.inline.} = self.dynamicCppCall("squeeze", dim).to(Tensor)
proc squeeze_u*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("squeeze_").to(Tensor)
proc squeeze_u*(self: Tensor, dim: int64): Tensor {.inline.} = self.dynamicCppCall("squeeze_", dim).to(Tensor)
proc stft*(self: Tensor, n_fft: int64, hop_length: int64, win_length: int64, window: Tensor, normalized: bool = false, onesided: bool = true): Tensor {.inline.} = self.dynamicCppCall("stft", n_fft, hop_length, win_length, window, normalized, onesided).to(Tensor)
proc stride*(self: Tensor, dim: int64): int64 {.inline.} = self.dynamicCppCall("stride", dim).to(int64)
proc sum*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("sum").to(Tensor)
proc u_sum*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("_sum").to(Tensor)
proc sqrt*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("sqrt").to(Tensor)
proc sqrt_u*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("sqrt_").to(Tensor)
proc std*(self: Tensor, unbiased: bool = true): Tensor {.inline.} = self.dynamicCppCall("std", unbiased).to(Tensor)
proc std*(self: Tensor, dim: int64, unbiased: bool = true, keepdim: bool = false): Tensor {.inline.} = self.dynamicCppCall("std", dim, unbiased, keepdim).to(Tensor)
proc prod*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("prod").to(Tensor)
proc u_prod*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("_prod").to(Tensor)
proc prod*(self: Tensor, dim: int64, keepdim: bool = false): Tensor {.inline.} = self.dynamicCppCall("prod", dim, keepdim).to(Tensor)
proc u_prod*(self: Tensor, dim: int64, keepdim: bool = false): Tensor {.inline.} = self.dynamicCppCall("_prod", dim, keepdim).to(Tensor)
proc t*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("t").to(Tensor)
proc t_u*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("t_").to(Tensor)
proc tan*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("tan").to(Tensor)
proc tan_u*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("tan_").to(Tensor)
proc tanh*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("tanh").to(Tensor)
proc tanh_u*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("tanh_").to(Tensor)
proc transpose*(self: Tensor, dim0: int64, dim1: int64): Tensor {.inline.} = self.dynamicCppCall("transpose", dim0, dim1).to(Tensor)
proc transpose_u*(self: Tensor, dim0: int64, dim1: int64): Tensor {.inline.} = self.dynamicCppCall("transpose_", dim0, dim1).to(Tensor)
proc trunc*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("trunc").to(Tensor)
proc trunc_u*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("trunc_").to(Tensor)
proc type_as*(self: Tensor, other: Tensor): Tensor {.inline.} = self.dynamicCppCall("type_as", other).to(Tensor)
proc unsqueeze*(self: Tensor, dim: int64): Tensor {.inline.} = self.dynamicCppCall("unsqueeze", dim).to(Tensor)
proc unsqueeze_u*(self: Tensor, dim: int64): Tensor {.inline.} = self.dynamicCppCall("unsqueeze_", dim).to(Tensor)
proc avar*(self: Tensor, unbiased: bool = true): Tensor {.inline.} = self.dynamicCppCall("var", unbiased).to(Tensor)
proc avar*(self: Tensor, dim: int64, unbiased: bool = true, keepdim: bool = false): Tensor {.inline.} = self.dynamicCppCall("var", dim, unbiased, keepdim).to(Tensor)
proc view_as*(self: Tensor, other: Tensor): Tensor {.inline.} = self.dynamicCppCall("view_as", other).to(Tensor)
proc where*(self: Tensor, condition: Tensor, other: Tensor): Tensor {.inline.} = self.dynamicCppCall("where", condition, other).to(Tensor)
proc u_s_where*(self: Tensor, condition: Tensor, other: Tensor): Tensor {.inline.} = self.dynamicCppCall("_s_where", condition, other).to(Tensor)
proc u_standard_gamma_grad*(self: Tensor, output: Tensor): Tensor {.inline.} = self.dynamicCppCall("_standard_gamma_grad", output).to(Tensor)
proc clone*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("clone").to(Tensor)
proc resize_as_u*(self: Tensor, the_template: Tensor): Tensor {.inline.} = self.dynamicCppCall("resize_as_", the_template).to(Tensor)
proc zero_u*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("zero_").to(Tensor)
proc to_dense*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("to_dense").to(Tensor)
proc u_sparseDims*(self: Tensor): int64 {.inline.} = self.dynamicCppCall("_sparseDims").to(int64)
proc u_dimI*(self: Tensor): int64 {.inline.} = self.dynamicCppCall("_dimI").to(int64)
proc u_denseDims*(self: Tensor): int64 {.inline.} = self.dynamicCppCall("_denseDims").to(int64)
proc u_dimV*(self: Tensor): int64 {.inline.} = self.dynamicCppCall("_dimV").to(int64)
proc u_nnz*(self: Tensor): int64 {.inline.} = self.dynamicCppCall("_nnz").to(int64)
proc coalesce*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("coalesce").to(Tensor)
proc is_coalesced*(self: Tensor): bool {.inline.} = self.dynamicCppCall("is_coalesced").to(bool)
proc u_indices*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("_indices").to(Tensor)
proc u_values*(self: Tensor): Tensor {.inline.} = self.dynamicCppCall("_values").to(Tensor)
proc numel*(self: Tensor): int64 {.inline.} = self.dynamicCppCall("numel").to(int64)
proc unbind*(self: Tensor, dim: int64 = 0): TensorList {.inline.} = self.dynamicCppCall("unbind", dim).to(TensorList)
proc get_device*(self: Tensor): int64 {.inline.} = self.dynamicCppCall("get_device").to(int64)
