FROM nvidia/cuda:9.2-cudnn7-devel-ubuntu18.04

RUN apt-get update && apt-get install -y build-essential git cmake python3-pip libmpfr-dev libgmp-dev wget

RUN pip3 install pyyaml
RUN pip3 install typing

RUN cd && \
wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh

RUN cd && \
chmod +x Miniconda3-latest-Linux-x86_64.sh && \
./Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda3

RUN /root/miniconda3/bin/conda install conda-build anaconda-client

SHELL ["/bin/bash", "-c"]
ENV PATH /root/miniconda3/bin:$PATH

ARG PYTORCH_COMMIT

RUN cd && \
git clone -b fragcolor-devel https://github.com/fragcolor-xyz/pytorch.git && \
cd pytorch && \
git reset --hard ${PYTORCH_COMMIT}

RUN cd && \
cd pytorch && \
git submodule init && \
git submodule update

ENV PYTORCH_PYTHON=python3

RUN conda create -n deps mkl mkl-include

RUN cd && \
cd pytorch && \
mkdir built && \
cd built && \
source activate deps && \
cmake -DCMAKE_INCLUDE_PATH=$CONDA_PREFIX/include -DCMAKE_LIBRARY_PATH=$CONDA_PREFIX/lib -DCMAKE_BUILD_TYPE=Release -DBUILD_ATEN_ONLY=ON -DCMAKE_INSTALL_PREFIX=`pwd`/output ../ && \
make -j10 && \
make install -j10 && \
make clean && \
cp ../tools/autograd/derivatives.yaml `pwd`/output/share/

COPY conda /root/conda

ARG TOKEN

RUN cd && cd conda && \
source activate deps && \
export PATH=$PATH:/root/miniconda3/bin && \
export ATEN=/root/pytorch/built/output && \
conda build cuda10.0 && \
conda build wasm

RUN anaconda -t ${TOKEN} upload --skip-existing /root/miniconda3/conda-bld/linux-64/wasm-*.tar.bz2
RUN anaconda -t ${TOKEN} upload --skip-existing /root/miniconda3/conda-bld/linux-64/cuda10.0-*.tar.bz2

RUN cd && cd conda && \
source activate deps && \
export PATH=$PATH:/root/miniconda3/bin && \
export ATEN=/root/pytorch/built/output && \
conda build aten

RUN anaconda -t ${TOKEN} upload /root/miniconda3/conda-bld/linux-64/aten-*.tar.bz2
